package com.mycompany.collagemanagementapp;

import com.mycompany.collagemanagementapp.Images.DashboardLibrarian;
import com.mycompany.collagemanagementapp.ConnectionUtil;
import com.mycompany.collagemanagementapp.DashboardAdmin;
import com.mycompany.collagemanagementapp.UserListAdmin;
import com.mycompany.collagemanagementapp.utilities.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kumra
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        pnlWhite = new javax.swing.JPanel();
        lbLoginMessage = new javax.swing.JLabel();
        lbAccountLogin = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        tfUserID = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        lbErrorText = new javax.swing.JLabel();
        cbLoginType = new javax.swing.JComboBox<>();
        lbEmail = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbUserType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(0, 0, 0));
        pnlBackground.setPreferredSize(new java.awt.Dimension(700, 500));

        pnlMain.setBackground(new java.awt.Color(100, 130, 173));
        pnlMain.setPreferredSize(new java.awt.Dimension(695, 495));

        pnlWhite.setBackground(new java.awt.Color(226, 218, 214));

        lbLoginMessage.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbLoginMessage.setText("      Hey , Enter your details to sign into your account");

        lbAccountLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbAccountLogin.setText("Account Login");

        btnLogin.setBackground(new java.awt.Color(100, 130, 173));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.MatteBorder(null));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        tfUserID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUserIDFocusGained(evt);
            }
        });
        tfUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserIDActionPerformed(evt);
            }
        });

        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        lbErrorText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbErrorText.setForeground(new java.awt.Color(255, 51, 51));

        cbLoginType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Others" }));

        lbEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbEmail.setText("Email");

        lbPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbPassword.setText("Password");

        lbUserType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbUserType.setText("User Type");

        javax.swing.GroupLayout pnlWhiteLayout = new javax.swing.GroupLayout(pnlWhite);
        pnlWhite.setLayout(pnlWhiteLayout);
        pnlWhiteLayout.setHorizontalGroup(
            pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWhiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLoginMessage)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWhiteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbAccountLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWhiteLayout.createSequentialGroup()
                .addGap(19, 38, Short.MAX_VALUE)
                .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbErrorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlWhiteLayout.createSequentialGroup()
                                .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbPassword))
                                .addGap(29, 29, 29)
                                .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfUserID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlWhiteLayout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)))
                        .addGroup(pnlWhiteLayout.createSequentialGroup()
                            .addComponent(lbUserType)
                            .addGap(28, 28, 28)
                            .addComponent(cbLoginType, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        pnlWhiteLayout.setVerticalGroup(
            pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWhiteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbAccountLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLoginMessage)
                .addGap(32, 32, 32)
                .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlWhiteLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPassword))
                .addGap(26, 26, 26)
                .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUserType)
                    .addComponent(cbLoginType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(pnlWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnlWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      if(tfUserID.getText().isEmpty() || tfPassword.getText().isEmpty())
        {
            lbErrorText.setText("Email and pwd are required");
        }
   else{
         if(cbLoginType.getSelectedIndex()==0)
         {
         if((tfUserID.getText().equals("dhruv") && tfPassword.getText().equals("123")))
            {
            DashboardAdmin dashboard= new DashboardAdmin();
            dashboard.setVisible(true);
            this.dispose(); 

            }
        else{
                   lbErrorText.setText("Invalid credentials");
          }
         }
         else{
             try {
                 Connection conn = ConnectionUtil.getInstance();
                 PreparedStatement  pst = conn.prepareStatement("select * from userlist where email=? && password=?");
                 pst.setString(1,tfUserID.getText());
                 pst.setString(2,tfPassword.getText());
             
                 
                ResultSet rs = pst.executeQuery();
                
                if(rs.next())
                {
                    UserSession session = UserSession.getInstance();
                    session.setId(rs.getInt("id"));
                 if(rs.getString("usertype").equalsIgnoreCase("teacher"))  
                    {
                        session.setUserType(1);
                     DashboardTeacher dashboardTeacher = new DashboardTeacher();
                     dashboardTeacher.setVisible(true);
                     this.dispose();
                    }
                 else if(rs.getString("usertype").equalsIgnoreCase("accountant"))
                    {
                            session.setUserType(2);
                     DashboardAccountant dashboardAccountant = new DashboardAccountant();
                     dashboardAccountant.setVisible(true);
                     this.dispose();
                    }else if("librarian".equals(rs.getString("usertype")))
                    {
                        session.setUserType(3);
                     DashboardLibrarian dashboardLibrarian = new DashboardLibrarian();
                     dashboardLibrarian.setVisible(true);
                     this.dispose();
                    }
                }
                else{
                lbErrorText.setText("Invalid credentials"); 
                }

             } catch (SQLException ex) {
                 Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
   }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tfUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserIDActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfUserIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserIDFocusGained
        
    }//GEN-LAST:event_tfUserIDFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbLoginType;
    private javax.swing.JLabel lbAccountLogin;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbErrorText;
    private javax.swing.JLabel lbLoginMessage;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUserType;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlWhite;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUserID;
    // End of variables declaration//GEN-END:variables
}
